# -*- coding: utf-8 -*-
"""Assingment-1code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kgwt1ArcrBa17IsygvTElioV5U1PIOv7
"""

import random 

#Function for roll the dice.
def roll_the_dice(Event):
    n_simulation=100000
    count=0
    #do this experiment 100000 times 
    for i in range(n_simulation):

        # three  dice are rolled simutaneously times 
        X1=random.randint(1,6)
        X2=random.randint(1,6)
        X3=random.randint(1,6)


        #event E i.e X3 = 4
        if Event=='E':
            if X3==4:
                count+=1

        #event F i.e  X1==6 and X2==5     
        elif Event=='F':
            if X1==6 and X2==5 :
                count+=1
        
        #to X1==6 and X2==5 and X3==4
        else :
            if X1==6 and X2==5 and X3==4:
                count+=1

    return count/n_simulation

a = round(roll_the_dice('E and F'),5)  #P(E and F)
b = round(roll_the_dice('F'),5)        #P(F)

print("Probability of getting 4 at third roll, Pr(X3 = 4) = ",round(roll_the_dice('E'),5))
print("Probability of getting 6 and 5 on first and second roll resp., Pr( X1=6 ,X2=5) = ",round(roll_the_dice('F'),5))
print("Probability of (6,5,4), Pr(X1=6 , X2=5 , X3=4) = ",round(roll_the_dice('E and F'),5))
print('probability P(X3= 4| X2=5 , X1= 6) = ',round(a/b,5))
